Remove importing java logger
Causes all sorts of problems apparently

```
ERROR: uninitialized constant Java::JavaUtilLogging::Logger::DEBUG
(NameError)
org/jruby/RubyModule.java:2677:in `const_missing'
```